services:
    cookie_bar.provider:
        class: Xtuc\CookieLawBundle\Services\CookieBarProvider

    cookielaw.listener:
        class: Xtuc\CookieLawBundle\Services\CookieLawListener
        arguments:
            - @cookie_bar.provider
        tags:
            - { name: kernel.event_listener, event: kernel.response }
